In [13]:
import pandas as pd

# Carregar os dados limpos
df = pd.read_csv('/Users/victorsabino36/Desktop/data_limpo_final.csv')

# Selecionar as colunas analisadas
colunas_selecionadas = [
    'Bankrupt?', 'Operating Gross Margin', 'Current Ratio', 'Quick Ratio', 
    'Debt ratio %', 'Net worth/Assets','Interest Expense Ratio', 
    'Total Asset Turnover', 'Working Capital to Total Assets', 'Cash Flow to Total Assets', 'ROA(C) before interest and depreciation before interest'
]

df_reduzido = df[colunas_selecionadas].copy()

In [15]:
# Mapear a coluna 'Bankrupt?' para uma versão mais descritiva
df_reduzido['Status'] = df_reduzido['Bankrupt?'].map({0: 'Não Falida', 1: 'Falida'})

# Remover a coluna original "Bankrupt?"
df_reduzido.drop(columns=['Bankrupt?'], inplace=True)

In [17]:
# Salvar como CSV para importar no Power BI
df_reduzido.to_csv('/Users/victorsabino36/Desktop/data_para_powerbi.csv', index=False)

print("Arquivo salvo com sucesso: data_para_powerbi_roi.csv")

Arquivo salvo com sucesso: data_para_powerbi_roi.csv

In [19]:
df_reduzido.head(15)

,Operating Gross Margin,Current Ratio,Quick Ratio,Debt ratio %,Net worth/Assets,Interest Expense Ratio,Total Asset Turnover,Working Capital to Total Assets,Cash Flow to Total Assets,ROA(C) before interest and depreciation before interest,Status
0,0.601457,0.002259,0.001208,0.207576,0.792424,0.629951,0.086957,0.672775,0.637555,NaN,Falida
1,0.610235,0.006016,0.004039,0.171176,0.828824,0.635172,0.064468,0.751111,0.641100,0.464291,Falida
2,0.601450,0.011543,0.005348,0.207516,0.792484,0.629631,0.014993,0.829502,0.642765,0.426071,Falida
3,0.583541,0.004194,0.002896,0.151465,0.848535,0.630228,0.089955,0.725754,0.579039,0.399844,Falida
4,0.598783,0.006022,0.003727,0.106509,0.893491,0.636055,0.175412,0.751822,0.622374,0.465022,Falida
5,0.590171,0.002740,0.000855,0.180427,0.819573,0.630184,0.095952,0.686729,0.637470,NaN,Falida
6,0.619950,0.004672,0.002869,0.216102,0.783898,0.629988,0.100450,0.729416,0.630419,NaN,Não Falida
7,0.601738,0.009657,0.007305,0.108202,0.891798,0.631379,0.218891,0.797005,0.641553,0.508361,Não Falida
8,0.603612,0.013499,0.011823,0.058591,0.941409,0.630915,0.154423,0.813738,0.649869,0.488519,Não Falida
9,0.599209,0.011475,0.007517,0.121293,0.878707,0.632188,NaN,0.825696,0.643428,0.495686,Não Falida
10,0.614026,0.006097,0.003449,0.103577,0.896423,0.631237,0.076462,0.751204,0.642950,0.482475,Não Falida
11,0.623712,0.008629,0.005123,0.094386,0.905614,0.632096,0.062969,0.769114,0.644570,0.444401,Não Falida
12,0.608131,0.006631,0.004029,0.144662,0.855338,0.632378,0.124438,0.760000,0.629827,0.491152,Não Falida
13,0.600578,0.010100,0.006447,0.106570,0.893430,0.640423,0.145427,0.791910,0.656023,0.474041,Não Falida
14,0.604686,0.018859,0.012023,0.089639,0.910361,0.631671,0.101949,0.802391,0.622835,0.506703,Não Falida